version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sql_anti_pattern
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
